def drawHelp(canvas,data):
    #char = PhotoImage(file = "Fa")
    if data.mode == "Help":
        canvas.create_rectangle(0,0,data.width,data.height, fill = "lavender")
        canvas.create_text(data.width//2, 75, text = "INSTRUCTIONS", font = "Monaco 55")
        canvas.create_text(250,150, text = "Each player starts out with 13 tiles.", font = "Monaco 15")
        canvas.create_text(380, 175, text = "Every turn, a player randomly selects a tile to add to their hand.", font = "Monaco 15")
        canvas.create_text(395, 200, text = "There are 4 kinds of tiles - Characters, Numbers, Lines, and Circles.", font = "Monaco 15")
        canvas.create_image(200, 250, image = data.fa)
        canvas.create_image(335, 250, image = data.bing)
        canvas.create_image(450,250, image = data.number)
        canvas.create_image(575,250, image = data.tiao)
        canvas.create_text(200, 290, text = "Character", font = "Monaco 10")
        canvas.create_text(325, 290, text = "Circle", font = "Monaco 10")
        canvas.create_text(450, 290, text = "Number", font = "Monaco 10")
        canvas.create_text(575, 290, text = "Line", font = "Monaco 10")
        canvas.create_text(360, 325, text = "The goal of the game is to get a legal hand.", font = "Monaco 15")
        canvas.create_text(363, 350, text = "A legal hand has 4 sets of 3 and one set of 2.", font = ("Monaco 15"))
        canvas.create_text(375, 375, text = "A set of 3 can be created through Peng(same tiles) or Chi(consecutive tiles).", font = "Monaco 15")
        canvas.create_text(360, 400, text = "The set of 2 must be of the same tile.", font = "Monaco 15")
        canvas.create_text(365, 425, text = "Press the space bar to progress through each turn.", font = "Monaco 15")
        canvas.create_text(365, 450, text = "Press r to add a random tile to your hand.", font = "Monaco 15")
        canvas.create_text(365, 475, text = "Click on a tile to select it.", font = "Monaco 15")
        canvas.create_text(365, 500, text = "Press the up arrow key to discard the clicked tile", font = "Monaco 15")  
        canvas.create_text(380, 550, text = "PRESS O TO GO BACK TO THE HOME SCREEN", font = "Monaco 30")